//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//namespace CalculatorWebApplication.CalculatorService {
    
    
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
//    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorService.CalculatorWebServicesSoap")]
//    public interface CalculatorWebServicesSoap {
        
//        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
//        int Add(int firstNumber, int secondNumber);
        
//        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
//        System.Threading.Tasks.Task<int> AddAsync(int firstNumber, int secondNumber);
//    }
    
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
//    public interface CalculatorWebServicesSoapChannel : CalculatorWebApplication.CalculatorService.CalculatorWebServicesSoap, System.ServiceModel.IClientChannel {
//    }
    
//    [System.Diagnostics.DebuggerStepThroughAttribute()]
//    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
//    public partial class CalculatorWebServicesSoapClient : System.ServiceModel.ClientBase<CalculatorWebApplication.CalculatorService.CalculatorWebServicesSoap>, CalculatorWebApplication.CalculatorService.CalculatorWebServicesSoap {
        
//        public CalculatorWebServicesSoapClient() {
//        }
        
//        public CalculatorWebServicesSoapClient(string endpointConfigurationName) : 
//                base(endpointConfigurationName) {
//        }
        
//        public CalculatorWebServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
//                base(endpointConfigurationName, remoteAddress) {
//        }
        
//        public CalculatorWebServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
//                base(endpointConfigurationName, remoteAddress) {
//        }
        
//        public CalculatorWebServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
//                base(binding, remoteAddress) {
//        }
        
//        public int Add(int firstNumber, int secondNumber) {
//            return base.Channel.Add(firstNumber, secondNumber);
//        }
        
//        public System.Threading.Tasks.Task<int> AddAsync(int firstNumber, int secondNumber) {
//            return base.Channel.AddAsync(firstNumber, secondNumber);
//        }
//    }
//}
